namespace HPD.Auth.Core.Interfaces;

/// <summary>
/// Abstraction for sending HPD.Auth transactional emails.
/// Implementations can use any email provider (SendGrid, SES, SMTP, etc.).
/// The interface is intentionally thin — implementations are responsible
/// for template rendering and delivery.
/// </summary>
public interface IHPDAuthEmailSender
{
    /// <summary>
    /// Send an email confirmation link to a newly registered user.
    /// </summary>
    /// <param name="email">Recipient email address.</param>
    /// <param name="userId">The user's ID (for building the confirmation URL).</param>
    /// <param name="token">The email confirmation token generated by Identity.</param>
    /// <param name="ct">Cancellation token.</param>
    Task SendEmailConfirmationAsync(
        string email,
        string userId,
        string token,
        CancellationToken ct = default);

    /// <summary>
    /// Send a password reset link.
    /// </summary>
    /// <param name="email">Recipient email address.</param>
    /// <param name="userId">The user's ID (for building the reset URL).</param>
    /// <param name="token">The password reset token generated by Identity.</param>
    /// <param name="ct">Cancellation token.</param>
    Task SendPasswordResetAsync(
        string email,
        string userId,
        string token,
        CancellationToken ct = default);

    /// <summary>
    /// Send a magic link (passwordless sign-in) to a user.
    /// </summary>
    /// <param name="email">Recipient email address.</param>
    /// <param name="link">The fully-constructed magic link URL.</param>
    /// <param name="ct">Cancellation token.</param>
    Task SendMagicLinkAsync(
        string email,
        string link,
        CancellationToken ct = default);

    /// <summary>
    /// Send a security alert when a login from a new device or location is detected.
    /// </summary>
    /// <param name="email">Recipient email address.</param>
    /// <param name="ipAddress">IP address of the login.</param>
    /// <param name="deviceInfo">Human-readable device/browser description.</param>
    /// <param name="ct">Cancellation token.</param>
    Task SendLoginAlertAsync(
        string email,
        string ipAddress,
        string deviceInfo,
        CancellationToken ct = default);
}
