using System;

namespace HPD.Agent;

/// <summary>
/// Metadata about a container (toolkit, skill, or other), used for collapsing and organization.
/// Generated by the source generator for toolkits marked with [Toolkit].
/// </summary>
public class ToolMetadata
{
    /// <summary>
    /// Container name (typically the class name or custom name from [Toolkit(Name = "...")]).
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Description of container capabilities (from [Toolkit] attribute).
    /// </summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// Names of all functions in this container.
    /// </summary>
    public string[] FunctionNames { get; set; } = Array.Empty<string>();

    /// <summary>
    /// Total number of functions in this container.
    /// </summary>
    public int FunctionCount { get; set; }

    /// <summary>
    /// Whether this toolkit is collapsed (functions hidden behind container).
    /// If true, the container should be collapsed (container generated).
    /// If false, all functions are always visible.
    /// </summary>
    public bool IsCollapsed { get; set; }
}
