using Microsoft.Extensions.AI;

namespace HPD.Agent;

/// <summary>
/// Factory for creating tool functions without reflection.
/// Contains direct delegate references to generated registration code.
/// Generated by HPDToolSourceGenerator per assembly.
/// </summary>
/// <remarks>
/// This record is the key to eliminating reflection in hot paths:
/// - CreateInstance: Direct constructor call (no Activator.CreateInstance!)
/// - CreateFunctions: Direct delegate to generated CreateTools method
/// - GetReferencedTools: Direct delegate to generated GetReferencedTools method
/// - GetReferencedFunctions: Direct delegate to generated GetReferencedFunctions method (Phase 4.5)
///
/// The source generator creates a ToolRegistry.g.cs file that initializes
/// an array of ToolFactory records with these delegates, enabling AOT-compatible
/// tool instantiation and function creation.
/// </remarks>
public record ToolFactory(
    /// <summary>
    /// Tool name (e.g., "MathTools", "FileSystemTools")
    /// </summary>
    string Name,

    /// <summary>
    /// Tool type (for type checking and compatibility)
    /// </summary>
    Type ToolType,

    /// <summary>
    /// Direct constructor call delegate - AOT-safe, no Activator.CreateInstance
    /// Example: () => new MathTools()
    /// </summary>
    Func<object> CreateInstance,

    /// <summary>
    /// Direct delegate to generated CreateTools method
    /// Example: (instance, ctx) => MathToolsRegistration.CreateTools((MathTools)instance, ctx)
    /// </summary>
    Func<object, IToolMetadata?, List<AIFunction>> CreateFunctions,

    /// <summary>
    /// Direct delegate to generated GetReferencedTools method
    /// Returns tool names that this tool's skills depend on
    /// </summary>
    Func<string[]> GetReferencedTools,

    /// <summary>
    /// Direct delegate to generated GetReferencedFunctions method (Phase 4.5)
    /// Returns map of tool name -> function names for selective registration
    /// </summary>
    Func<Dictionary<string, string[]>> GetReferencedFunctions
);
