using Microsoft.Extensions.AI;

namespace HPD.Agent;

/// <summary>
/// Factory for creating plugin functions without reflection.
/// Contains direct delegate references to generated registration code.
/// Generated by HPDPluginSourceGenerator per assembly.
/// </summary>
/// <remarks>
/// This record is the key to eliminating reflection in hot paths:
/// - CreateInstance: Direct constructor call (no Activator.CreateInstance!)
/// - CreateFunctions: Direct delegate to generated CreatePlugin method
/// - GetReferencedPlugins: Direct delegate to generated GetReferencedPlugins method
/// - GetReferencedFunctions: Direct delegate to generated GetReferencedFunctions method (Phase 4.5)
///
/// The source generator creates a PluginRegistry.g.cs file that initializes
/// an array of PluginFactory records with these delegates, enabling AOT-compatible
/// plugin instantiation and function creation.
/// </remarks>
public record PluginFactory(
    /// <summary>
    /// Plugin name (e.g., "MathPlugin", "FileSystemPlugin")
    /// </summary>
    string Name,

    /// <summary>
    /// Plugin type (for type checking and compatibility)
    /// </summary>
    Type PluginType,

    /// <summary>
    /// Direct constructor call delegate - AOT-safe, no Activator.CreateInstance
    /// Example: () => new MathPlugin()
    /// </summary>
    Func<object> CreateInstance,

    /// <summary>
    /// Direct delegate to generated CreatePlugin method
    /// Example: (instance, ctx) => MathPluginRegistration.CreatePlugin((MathPlugin)instance, ctx)
    /// </summary>
    Func<object, IPluginMetadata?, List<AIFunction>> CreateFunctions,

    /// <summary>
    /// Direct delegate to generated GetReferencedPlugins method
    /// Returns plugin names that this plugin's skills depend on
    /// </summary>
    Func<string[]> GetReferencedPlugins,

    /// <summary>
    /// Direct delegate to generated GetReferencedFunctions method (Phase 4.5)
    /// Returns map of plugin name -> function names for selective registration
    /// </summary>
    Func<Dictionary<string, string[]>> GetReferencedFunctions
);
