using Microsoft.AspNetCore.Routing;

namespace HPD.Agent.Adapters.AspNetCore.EndpointMapping;

/// <summary>
/// Convenience extension for mapping all registered adapters at once.
/// </summary>
public static class AdapterEndpointRouteBuilderExtensions
{
    /// <summary>
    /// Maps every adapter registered in the assembly via <see cref="HpdAdapterAttribute"/>
    /// to its default webhook path.
    /// </summary>
    /// <remarks>
    /// Equivalent to calling <c>MapXxxWebhook()</c> for each adapter individually.
    /// Uses the assembly-scoped <c>AdapterRegistry.All</c> array generated by the
    /// source generator — zero reflection after startup.
    /// </remarks>
    /// <example>
    /// <code>
    /// // Map all adapters at their default paths:
    /// app.MapHPDAdapters();
    ///
    /// // Or map individually with custom paths:
    /// app.MapSlackWebhook("/webhooks/slack");
    /// app.MapTeamsWebhook("/webhooks/teams");
    /// </code>
    /// </example>
    public static IEndpointRouteBuilder MapHPDAdapters(this IEndpointRouteBuilder app)
    {
        // AdapterRegistry.All is generated by the source generator at compile time.
        // This method is a no-op if no adapters are registered in the calling assembly.
        // Each adapter's MapEndpoint delegate calls the generated MapXxxWebhook() extension.
        foreach (var registration in GetRegistrations(app))
        {
            registration.MapEndpoint(app, registration.DefaultPath);
        }

        return app;
    }

    // Returns AdapterRegistry.All from the calling assembly via the generated type.
    // Resolved via a partial method so the generator can inject the right assembly reference.
    private static IEnumerable<AdapterRegistration> GetRegistrations(IEndpointRouteBuilder app)
    {
        // The generator emits AdapterRegistry in namespace HPD.Agent.Adapters.Generated.
        // We resolve it here by convention. If none are registered, returns empty.
        var registryType = app.ServiceProvider
            .GetService(typeof(IAdapterRegistryProvider)) as IAdapterRegistryProvider;

        return registryType?.GetAll() ?? [];
    }
}
