using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace HPD.Agent.Adapters.SourceGenerator.Generators;

/// <summary>
/// Generates {AdapterName}Registration.g.cs for each [HpdAdapter] class.
/// Emits AddXxxAdapter() and MapXxxWebhook() extension methods.
/// </summary>
internal static class RegistrationGenerator
{
    public static void Generate(
        SourceProductionContext context,
        IReadOnlyList<AdapterInfo> adapters)
    {
        foreach (var adapter in adapters)
        {
            var source = BuildSource(adapter);
            context.AddSource($"{adapter.ClassName}Registration.g.cs",
                SourceText.From(source, Encoding.UTF8));
        }
    }

    private static string BuildSource(AdapterInfo adapter)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.AspNetCore.Http;");
        sb.AppendLine("using Microsoft.AspNetCore.Routing;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine("using Microsoft.Extensions.Options;");
        sb.AppendLine("using HPD.Agent.Adapters;");
        sb.AppendLine("using HPD.Agent.Adapters.Session;");
        sb.AppendLine();

        var adapterName = adapter.Name; // e.g. "slack"
        var className   = adapter.ClassName; // e.g. "SlackAdapter"
        var configName  = $"{className}Config";
        // Capitalised for method names: "Slack"
        var pascal = char.ToUpper(adapterName[0]) + adapterName.Substring(1);

        sb.AppendLine($"namespace {adapter.Namespace};");
        sb.AppendLine();

        // ── DI extensions ──────────────────────────────────────────────────────
        sb.AppendLine($"public static partial class {className}ServiceCollectionExtensions");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>Registers the {pascal} adapter and its configuration.</summary>");
        sb.AppendLine($"    public static IServiceCollection Add{pascal}Adapter(");
        sb.AppendLine($"        this IServiceCollection services,");
        sb.AppendLine($"        Action<{configName}> configure)");
        sb.AppendLine("    {");
        sb.AppendLine($"        services.Configure(configure);");
        sb.AppendLine($"        services.TryAddSingleton<{className}>();");
        sb.AppendLine($"        services.TryAddSingleton<HPD.Agent.Adapters.Session.PlatformSessionMapper>();");
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        // ── Endpoint extensions ───────────────────────────────────────────────
        sb.AppendLine($"public static partial class {className}EndpointRouteBuilderExtensions");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>Maps the {pascal} webhook endpoint and wires up the adapter.</summary>");
        sb.AppendLine($"    public static IEndpointConventionBuilder Map{pascal}Webhook(");
        sb.AppendLine($"        this IEndpointRouteBuilder app,");
        sb.AppendLine($"        string path = \"/webhooks/{adapterName}\")");
        sb.AppendLine("    {");
        sb.AppendLine($"        var adapter = app.ServiceProvider.GetRequiredService<{className}>();");
        sb.AppendLine($"        return app.MapPost(path, (HttpContext ctx) => adapter.HandleWebhookAsync(ctx));");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
