using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace HPD.Agent.Adapters.SourceGenerator.Generators;

/// <summary>
/// Generates AdapterRegistry.g.cs — one assembly-scoped file listing every [HpdAdapter]
/// class. Used by MapHPDAdapters() to wire all adapters without reflection.
/// </summary>
internal static class RegistryGenerator
{
    public static void Generate(
        SourceProductionContext context,
        IReadOnlyList<AdapterInfo> adapters)
    {
        if (adapters.Count == 0) return;

        var source = BuildSource(adapters);
        context.AddSource("AdapterRegistry.g.cs",
            SourceText.From(source, Encoding.UTF8));
    }

    private static string BuildSource(IReadOnlyList<AdapterInfo> adapters)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using HPD.Agent.Adapters;");
        sb.AppendLine("using HPD.Agent.Adapters.AspNetCore;");
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.AspNetCore.Routing;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace HPD.Agent.Adapters.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>AOT-safe catalog of all adapters registered in this assembly.</summary>");
        sb.AppendLine("internal static class AdapterRegistry");
        sb.AppendLine("{");
        sb.AppendLine("    public static readonly AdapterRegistration[] All =");
        sb.AppendLine("    [");

        foreach (var adapter in adapters)
        {
            var pascal = char.ToUpper(adapter.Name[0]) + adapter.Name.Substring(1);
            var mapExpr = $"{adapter.Namespace}.{adapter.ClassName}EndpointRouteBuilderExtensions.Map{pascal}Webhook(app, path ?? \"/webhooks/{adapter.Name}\")";
            sb.AppendLine($"        new AdapterRegistration(");
            sb.AppendLine($"            Name: \"{adapter.Name}\",");
            sb.AppendLine($"            AdapterType: typeof({adapter.Namespace}.{adapter.ClassName}),");
            sb.AppendLine($"            MapEndpoint: (app, path) => {mapExpr},");
            sb.AppendLine($"            DefaultPath: \"/webhooks/{adapter.Name}\"),");
        }

        sb.AppendLine("    ];");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
