using System;

/// <summary>
/// Metadata about a container (plugin, skill, or other), used for scoping and organization.
/// Generated by the source generator for containers marked with [Scope].
/// </summary>
public class PluginMetadata
{
    /// <summary>
    /// Container name (typically the class name).
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Description of container capabilities (from [Scope] attribute).
    /// </summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// Names of all functions in this container.
    /// </summary>
    public string[] FunctionNames { get; set; } = Array.Empty<string>();

    /// <summary>
    /// Total number of functions in this container.
    /// </summary>
    public int FunctionCount { get; set; }

    /// <summary>
    /// Whether this container has the [Scope] attribute.
    /// If true, the container should be scoped (container generated).
    /// If false, all functions are always visible.
    /// </summary>
    public bool HasScopeAttribute { get; set; }
}
