using System.Text.Json;

namespace HPD.Agent.Middleware;

/// <summary>
/// Factory for creating middleware instances without reflection.
/// Contains direct delegate references to generated registration code.
/// Generated by HPDToolSourceGenerator per assembly.
/// </summary>
/// <remarks>
/// <para><b>Design Philosophy:</b></para>
/// <para>
/// This record is the key to eliminating reflection in hot paths:
/// </para>
/// <list type="bullet">
/// <item>CreateInstance: Direct constructor call (no Activator.CreateInstance!)</item>
/// <item>CreateFromConfig: Direct delegate to create instance from JSON config</item>
/// </list>
///
/// <para>
/// The source generator creates a MiddlewareRegistry.g.cs file that initializes
/// an array of MiddlewareFactory records with these delegates, enabling AOT-compatible
/// middleware instantiation.
/// </para>
/// </remarks>
public record MiddlewareFactory(
    /// <summary>
    /// Middleware name (e.g., "LoggingMiddleware", "RateLimitMiddleware").
    /// This is the EffectiveName from [Middleware(Name = "...")] or the class name.
    /// </summary>
    string Name,

    /// <summary>
    /// Middleware type (for type checking and DI resolution).
    /// </summary>
    Type MiddlewareType,

    /// <summary>
    /// Direct constructor call delegate - AOT-safe, no Activator.CreateInstance.
    /// Example: () => new LoggingMiddleware()
    /// Returns null if middleware has no parameterless constructor (requires DI or config).
    /// </summary>
    Func<IAgentMiddleware>? CreateInstance,

    // ========== CONFIG-BASED INSTANTIATION ==========

    /// <summary>
    /// Type of the config constructor parameter, if detected.
    /// Example: typeof(RateLimitConfig) for RateLimitMiddleware(RateLimitConfig config).
    /// Null if middleware has no config constructor.
    /// </summary>
    Type? ConfigType = null,

    /// <summary>
    /// Delegate to create a middleware instance from JSON config.
    /// Example: json => new RateLimitMiddleware(json.Deserialize&lt;RateLimitConfig&gt;()!)
    /// Null if middleware has no config constructor.
    /// </summary>
    Func<JsonElement, IAgentMiddleware>? CreateFromConfig = null,

    /// <summary>
    /// Whether this middleware requires DI (no parameterless or config constructor).
    /// When true, CreateInstance and CreateFromConfig are null - must use ServiceProvider.
    /// </summary>
    bool RequiresDI = false
);
