namespace HPD.Agent;

/// <summary>
/// AOT-compatible factory for middleware state types.
/// Generated by MiddlewareStateGenerator for each [MiddlewareState] type.
/// </summary>
/// <remarks>
/// <para><b>Design Philosophy:</b></para>
/// <para>
/// This record enables cross-assembly middleware state discovery by following the
/// ToolkitRegistry pattern. Each assembly with [MiddlewareState] types generates
/// a MiddlewareStateRegistry.g.cs containing an array of these factories.
/// </para>
/// <list type="bullet">
/// <item>Deserialize: AOT-safe JSON deserialization (no reflection)</item>
/// <item>Serialize: AOT-safe JSON serialization (no reflection)</item>
/// <item>Instance-scoped: Factories are registered per-agent, not globally</item>
/// </list>
/// </remarks>
public record MiddlewareStateFactory(
    /// <summary>
    /// Fully-qualified type name used as the storage key.
    /// Example: "HPD.Agent.Memory.PlanModePersistentStateData"
    /// </summary>
    string FullyQualifiedName,

    /// <summary>
    /// The state type (for type checks and debugging).
    /// </summary>
    Type StateType,

    /// <summary>
    /// Generated property/extension method name.
    /// Example: "PlanModePersistent" for PlanModePersistentStateData.
    /// </summary>
    string PropertyName,

    /// <summary>
    /// Schema version for migration support.
    /// From [MiddlewareState(Version = N)] attribute.
    /// </summary>
    int Version,

    /// <summary>
    /// Whether this state should persist to session across runs.
    /// From [MiddlewareState(Persistent = true)] attribute.
    /// </summary>
    bool Persistent,

    /// <summary>
    /// AOT-safe deserializer delegate.
    /// Example: json => JsonSerializer.Deserialize&lt;MyStateData&gt;(json, options)
    /// </summary>
    Func<string, object?> Deserialize,

    /// <summary>
    /// AOT-safe serializer delegate.
    /// Example: state => JsonSerializer.Serialize((MyStateData)state, options)
    /// </summary>
    Func<object, string> Serialize
);
