namespace HPD.Agent.Adapters;

/// <summary>
/// Marks a <c>record</c> type as a webhook payload that should be included in the
/// assembly's <c>AdaptersJsonSerializerContext</c> generated by the source generator.
/// </summary>
/// <remarks>
/// Every record decorated with this attribute is automatically registered for
/// AOT-safe source-generated JSON serialization. No manual <c>[JsonSerializable]</c>
/// maintenance required.
/// <para>
/// The type must be a <c>record</c> — the generator emits diagnostic <c>HPD-A006</c>
/// if a non-record type is decorated.
/// </para>
/// </remarks>
[AttributeUsage(AttributeTargets.Class, Inherited = false)]
public sealed class WebhookPayloadAttribute : Attribute { }
