using System.Text.Json;
using Microsoft.Extensions.AI;

namespace HPD.Agent;

/// <summary>
/// Factory for creating toolkit instances without reflection.
/// Contains direct delegate references to generated registration code.
/// Generated by HPDToolSourceGenerator per assembly.
/// </summary>
/// <remarks>
/// <para><b>Design Philosophy:</b></para>
/// <para>
/// This record is the key to eliminating reflection in hot paths:
/// </para>
/// <list type="bullet">
/// <item>CreateInstance: Direct constructor call (no Activator.CreateInstance!)</item>
/// <item>CreateFunctions: Direct delegate to generated CreateToolkit method</item>
/// <item>GetReferencedToolkits: Direct delegate to generated GetReferencedToolkits method</item>
/// <item>GetReferencedFunctions: Direct delegate to generated GetReferencedFunctions method</item>
/// </list>
///
/// <para>
/// The source generator creates a ToolkitRegistry.g.cs file that initializes
/// an array of ToolkitFactory records with these delegates, enabling AOT-compatible
/// toolkit instantiation and function creation.
/// </para>
/// </remarks>
public record ToolkitFactory(
    // ========== EXISTING FIELDS ==========

    /// <summary>
    /// Toolkit name (e.g., "MathToolkit", "SearchToolkit").
    /// Always the class name (CustomName support removed).
    /// </summary>
    string Name,

    /// <summary>
    /// Toolkit type (for type checking and compatibility)
    /// </summary>
    Type ToolkitType,

    /// <summary>
    /// Direct constructor call delegate - AOT-safe, no Activator.CreateInstance
    /// Example: () => new MathToolkit()
    /// </summary>
    Func<object> CreateInstance,

    /// <summary>
    /// Direct delegate to generated CreateToolkit method.
    /// Example: (instance, ctx) => MathToolkitRegistration.CreateToolkit((MathToolkit)instance, ctx)
    /// </summary>
    Func<object, IToolMetadata?, List<AIFunction>> CreateFunctions,

    /// <summary>
    /// Direct delegate to generated GetReferencedToolkits method.
    /// Returns toolkit names that this toolkit's skills depend on.
    /// </summary>
    Func<string[]> GetReferencedToolkits,

    /// <summary>
    /// Direct delegate to generated GetReferencedFunctions method.
    /// Returns map of toolkit name -> function names for selective registration.
    /// </summary>
    Func<Dictionary<string, string[]>> GetReferencedFunctions,

    // ========== NEW: COLLAPSING METADATA (from [Collapse] attribute) ==========

    /// <summary>
    /// Whether this toolkit has a description (from [Collapse("description")]).
    /// Description presence = collapsible (functions hidden behind container).
    /// </summary>
    bool HasDescription = false,

    /// <summary>
    /// Description from [Collapse] attribute (if present).
    /// Used for the container function description when collapsed.
    /// </summary>
    string? Description = null,

    /// <summary>
    /// Instructions returned as FUNCTION RESULT when container is expanded.
    /// From [Collapse(FunctionResult = "...")] or method reference.
    /// </summary>
    string? FunctionResult = null,

    /// <summary>
    /// Instructions injected into SYSTEM PROMPT while expanded.
    /// From [Collapse(SystemPrompt = "...")] or method reference.
    /// </summary>
    string? SystemPrompt = null,

    // ========== NEW: CONFIG-BASED INSTANTIATION ==========

    /// <summary>
    /// Type of the config constructor parameter, if detected.
    /// Example: typeof(SearchToolkitConfig) for SearchToolkit(SearchToolkitConfig config).
    /// Null if toolkit has no config constructor.
    /// </summary>
    Type? ConfigType = null,

    /// <summary>
    /// Delegate to create a toolkit instance from JSON config.
    /// Example: json => new SearchToolkit(json.Deserialize&lt;SearchToolkitConfig&gt;()!)
    /// Null if toolkit has no config constructor.
    /// </summary>
    Func<JsonElement, object>? CreateFromConfig = null,

    // ========== NEW: METADATA DESERIALIZATION ==========

    /// <summary>
    /// Metadata type from [AIFunction&lt;TMetadata&gt;] on toolkit methods.
    /// Used to deserialize ToolkitReference.Metadata at resolution time.
    /// Example: typeof(SearchContext) for [AIFunction&lt;SearchContext&gt;].
    /// Null if toolkit methods don't use typed metadata.
    /// </summary>
    Type? MetadataType = null,

    // ========== NEW: SELECTIVE FUNCTION REGISTRATION ==========

    /// <summary>
    /// All function names in this toolkit for selective registration.
    /// Example: new[] { "WebSearch", "ImageSearch", "NewsSearch" }
    /// Used to validate ToolkitReference.Functions at resolution time.
    /// </summary>
    string[]? FunctionNames = null
);
